#!/usr/bin/env python3
"""Localized learner-facing curriculum for the three modern labs.

This data is intentionally separate from the historical v1.7.x parity data.
It raises the learner-facing teaching depth without changing any mechanism,
state transition, or Quick Assign response schema.
"""

from __future__ import annotations


LOCALES = ("en", "zh", "vi", "es")


COMMON = {
    "en": {
        "featured_summary": "✨ Featured experiment",
        "core_question": "Core question",
        "run_watch": "Run and watch",
        "start_featured": "Start featured experiment",
        "scenarios_summary": "🎯 Try these scenarios first",
        "scenarios_intro": "Pick a scenario, predict what should happen, then apply it and compare the result with your prediction.",
        "scenario": "Scenario",
        "predict_first": "Predict first",
        "explain_after": "Explain afterward",
        "apply": "Apply and compare",
        "applied": "Applied; compare the result",
        "jump": "↓ Read the step-by-step explanation",
        "before": "Before you read",
        "terms": "Terms used in this explanation",
        "teachers": "For teachers",
        "curriculum": "Curriculum",
        "pre": "Pre-exploration prompts",
        "post": "Post-exploration prompts",
        "misconceptions": "Misconceptions to test",
        "a11y_summary": "♿ Text and keyboard support",
        "a11y_title": "Text and keyboard support",
        "a11y_intro": "Use Tab and Shift+Tab to move through controls. Use Enter or Space on buttons and arrow keys on sliders or select controls.",
        "state_link": "Read the current model state in the applet’s text-state panel.",
        "a11y_note": "Important results are available as text and do not depend only on color or motion. This does not replace a full human assistive-technology audit.",
        "back_controls": "↑ Back to the applet controls",
    },
    "zh": {
        "featured_summary": "✨ 精选实验",
        "core_question": "核心问题",
        "run_watch": "运行并观察",
        "start_featured": "开始精选实验",
        "scenarios_summary": "🎯 先试试这些情境",
        "scenarios_intro": "选择一个情境，先预测结果，再应用设置，并把实际结果与预测比较。",
        "scenario": "情境",
        "predict_first": "先预测",
        "explain_after": "之后解释",
        "apply": "应用并比较",
        "applied": "已应用；请比较结果",
        "jump": "↓ 阅读分步说明",
        "before": "阅读前先准备",
        "terms": "本说明使用的术语",
        "teachers": "教师参考",
        "curriculum": "课程内容",
        "pre": "探索前问题",
        "post": "探索后问题",
        "misconceptions": "需要检验的误解",
        "a11y_summary": "♿ 文本与键盘支持",
        "a11y_title": "文本与键盘支持",
        "a11y_intro": "使用 Tab 和 Shift+Tab 在控件之间移动。按钮使用 Enter 或空格键，滑块与选择控件使用方向键。",
        "state_link": "在 applet 的文本状态面板中读取当前模型状态。",
        "a11y_note": "重要结果同时以文本提供，不只依赖颜色或动画。此功能不能替代完整的人工辅助技术审计。",
        "back_controls": "↑ 返回 applet 控件",
    },
    "vi": {
        "featured_summary": "✨ Thí nghiệm nổi bật",
        "core_question": "Câu hỏi cốt lõi",
        "run_watch": "Chạy và quan sát",
        "start_featured": "Bắt đầu thí nghiệm nổi bật",
        "scenarios_summary": "🎯 Hãy thử các tình huống này trước",
        "scenarios_intro": "Chọn một tình huống, dự đoán điều sẽ xảy ra, rồi áp dụng và so sánh kết quả với dự đoán.",
        "scenario": "Tình huống",
        "predict_first": "Dự đoán trước",
        "explain_after": "Giải thích sau",
        "apply": "Áp dụng và so sánh",
        "applied": "Đã áp dụng; hãy so sánh kết quả",
        "jump": "↓ Đọc phần giải thích từng bước",
        "before": "Trước khi đọc",
        "terms": "Thuật ngữ dùng trong phần giải thích",
        "teachers": "Dành cho giáo viên",
        "curriculum": "Nội dung học",
        "pre": "Câu hỏi trước khi khám phá",
        "post": "Câu hỏi sau khi khám phá",
        "misconceptions": "Những ngộ nhận cần kiểm tra",
        "a11y_summary": "♿ Hỗ trợ văn bản và bàn phím",
        "a11y_title": "Hỗ trợ văn bản và bàn phím",
        "a11y_intro": "Dùng Tab và Shift+Tab để di chuyển. Dùng Enter hoặc Space cho nút và phím mũi tên cho thanh trượt hoặc ô chọn.",
        "state_link": "Đọc trạng thái mô hình hiện tại trong bảng trạng thái văn bản của applet.",
        "a11y_note": "Kết quả quan trọng có dạng văn bản và không chỉ phụ thuộc vào màu sắc hay chuyển động. Tính năng này không thay thế kiểm tra thủ công đầy đủ bằng công nghệ hỗ trợ.",
        "back_controls": "↑ Quay lại điều khiển applet",
    },
    "es": {
        "featured_summary": "✨ Experimento destacado",
        "core_question": "Pregunta central",
        "run_watch": "Ejecuta y observa",
        "start_featured": "Iniciar el experimento destacado",
        "scenarios_summary": "🎯 Prueba primero estos escenarios",
        "scenarios_intro": "Elige un escenario, predice qué ocurrirá, aplícalo y compara el resultado con tu predicción.",
        "scenario": "Escenario",
        "predict_first": "Predice primero",
        "explain_after": "Explica después",
        "apply": "Aplicar y comparar",
        "applied": "Aplicado; compara el resultado",
        "jump": "↓ Leer la explicación paso a paso",
        "before": "Antes de leer",
        "terms": "Términos usados en esta explicación",
        "teachers": "Para docentes",
        "curriculum": "Contenido",
        "pre": "Preguntas antes de explorar",
        "post": "Preguntas después de explorar",
        "misconceptions": "Ideas erróneas que conviene comprobar",
        "a11y_summary": "♿ Soporte de texto y teclado",
        "a11y_title": "Soporte de texto y teclado",
        "a11y_intro": "Usa Tab y Shift+Tab para moverte. Usa Enter o Espacio en botones y las flechas en deslizadores o selectores.",
        "state_link": "Lee el estado actual del modelo en el panel de estado textual del applet.",
        "a11y_note": "Los resultados importantes están disponibles como texto y no dependen solo del color o del movimiento. Esto no sustituye una auditoría humana completa con tecnologías de apoyo.",
        "back_controls": "↑ Volver a los controles del applet",
    },
}


LABS = {
    "transformer-language-model": {
        "state_id": "stateText",
        "featured": 1,
        "settings": [
            {"scenario": "canonical"},
            {"scenario": "mask"},
            {"scenario": "order"},
            {"scenario": "qk"},
            {"scenario": "temperature"},
        ],
        "copy": {
            "en": {
                "primer": "A Transformer turns tokens into vectors, lets each position mix permitted earlier information, and converts the final vector into next-token probabilities. This lab keeps every number small enough to inspect.",
                "terms": [
                    ("Token", "A piece of text represented by one ID in this toy vocabulary."),
                    ("Embedding", "The starting vector for a token."),
                    ("Position vector", "Extra values that tell the model where a token appears."),
                    ("Query, key, value", "Three vectors used to score and mix information."),
                    ("Causal mask", "A rule that blocks attention to future positions."),
                    ("Attention weight", "A softmax-normalized coefficient used to mix value vectors."),
                    ("Logit", "An unnormalized score for a possible next token."),
                    ("Temperature", "A scale applied to fixed logits before softmax."),
                ],
                "scenarios": [
                    {"title":"From prompt to prediction","question":"How does the final token become a probability distribution?","run":"Use “I like cats” with positions and the causal mask on, then follow the final token through all four stages.","predict":"Predict which permitted source position will receive the largest attention weight.","explain":"Explain how the selected token’s final state becomes logits and probabilities."},
                    {"title":"The causal mask blocks the future","question":"Why must a next-token model hide later positions?","run":"Apply the mask-leak scenario and compare the same attention row with the mask on and off.","predict":"Predict which previously blocked cells will gain nonzero weight.","explain":"Explain why using a future token would make the next-token test invalid."},
                    {"title":"Word order changes the representation","question":"Why are the same words in a different order not the same input?","run":"Apply the order scenario, then compare the final-token vector with position information on and off.","predict":"Predict where the first numerical difference will appear.","explain":"Explain what position vectors add that token embeddings alone do not."},
                    {"title":"One score change can spread forward","question":"How can a small query or key change affect the final prediction?","run":"Apply the Q/K perturbation and trace the changed score, attention weight, final state, and probability.","predict":"Predict which source token’s weight will move most.","explain":"Explain why changing a score can affect every normalized weight in the row."},
                    {"title":"Temperature changes confidence, not learning","question":"What changes when temperature changes but model weights stay fixed?","run":"Apply the temperature scenario and compare the logits with the probability distribution.","predict":"Predict whether the top token changes or only the sharpness changes.","explain":"Explain why temperature does not retrain the model."},
                ],
                "sections": [
                    ("1. Tokenize and add position", ["The toy tokenizer maps each displayed piece to a fixed ID. An embedding table turns each ID into a vector.", "A position vector is added to that embedding. Without it, repeated tokens begin with the same representation wherever they appear."]),
                    ("2. Score permitted source positions", ["The model derives a query, key, and value vector at each position. A query–key dot product measures one numerical match, then division by the square root of the key dimension keeps scores in a workable range.", "The causal mask replaces future scores before softmax. A masked position receives no attention weight."]),
                    ("3. Mix values, not token labels", ["Softmax turns the permitted scores into weights that sum to one. The attention output is the weighted sum of value vectors.", "A large weight matters only through the value it multiplies. The weight alone is not a complete explanation of the prediction."]),
                    ("4. Convert the final state into a prediction", ["The toy block combines the attention output with its residual and feed-forward path. Output weights map the final state to one logit per vocabulary item.", "Softmax converts logits into probabilities. Temperature rescales those same logits: lower values sharpen the distribution and higher values flatten it."]),
                    ("What this model leaves out", ["This deterministic block is not pretrained, does not learn during the activity, and does not reproduce a production language model. Real systems use many layers, heads, larger vocabularies, learned parameters, and a separate generation rule.", "Attention weights show one mixing operation. They do not reveal a model’s complete reasoning, understanding, or causal explanation."]),
                ],
                "teacher": {"curriculum":"Tokenization, embeddings, position, query–key scores, causal masking, softmax, logits, temperature, and evidence limits.","pre":["What information is lost if token order is ignored?","Why should a next-token predictor be unable to read the next token?","What is the difference between a score and a probability?"],"post":["Change one token and identify the first changed number.","Turn the mask off. Which calculation becomes invalid for next-token prediction?","Change temperature. Which values stay fixed?","Why is the largest attention weight not the whole explanation?"],"misconceptions":"one token always equals one word; attention is understanding; the largest weight is the complete reason; temperature changes learned weights; the highest-probability token must always be selected."},
            },
            "zh": {
                "primer":"Transformer 先把词元变成向量，让每个位置混合允许看到的较早信息，再把最终向量转换为下一词元概率。本实验把所有数值控制在可逐项检查的范围内。",
                "terms":[("词元","在这个玩具词表中由一个 ID 表示的文本片段。"),("嵌入","词元的起始向量。"),("位置向量","告诉模型词元所在位置的附加数值。"),("Query、Key、Value","用于计算匹配分数和混合信息的三类向量。"),("因果掩码","阻止当前位置关注未来位置的规则。"),("注意力权重","经 softmax 归一化、用于混合 value 向量的系数。"),("Logit","某个候选下一词元在归一化前的分数。"),("温度","softmax 前对固定 logits 使用的缩放值。")],
                "scenarios":[
                    {"title":"从提示词到预测","question":"最后一个词元怎样变成概率分布？","run":"使用“I like cats”，开启位置与因果掩码，沿四个阶段追踪最后一个词元。","predict":"预测哪个允许的源位置会得到最大的注意力权重。","explain":"解释所选词元的最终状态怎样变成 logits 和概率。"},
                    {"title":"因果掩码挡住未来","question":"为什么下一词元模型必须隐藏后面的位置？","run":"应用掩码泄漏情境，比较同一注意力行在开启和关闭掩码时的结果。","predict":"预测哪些原本被挡住的单元格会获得非零权重。","explain":"解释为什么读取未来词元会让下一词元测试失效。"},
                    {"title":"词序改变表示","question":"为什么相同词语换一个顺序就不是相同输入？","run":"应用词序情境，比较开启和关闭位置信息时最后词元的向量。","predict":"预测第一处数值差异会出现在哪里。","explain":"解释位置向量提供了词元嵌入本身没有的什么信息。"},
                    {"title":"一个分数变化会向后传播","question":"Query 或 key 的小变化怎样影响最终预测？","run":"应用 Q/K 扰动，追踪变化的分数、注意力权重、最终状态与概率。","predict":"预测哪个源词元的权重变化最大。","explain":"解释为什么改变一个分数会影响这一行所有归一化权重。"},
                    {"title":"温度改变置信度，不改变学习","question":"模型权重不变而温度变化时，究竟改变了什么？","run":"应用温度情境，比较 logits 与概率分布。","predict":"预测最高概率词元会改变，还是只有分布尖锐程度改变。","explain":"解释为什么温度不会重新训练模型。"},
                ],
                "sections":[("1. 词元化并加入位置",["玩具 tokenizer 把每个显示的文本片段映射为固定 ID，嵌入表再把 ID 变成向量。","位置向量与嵌入相加。没有它时，相同词元无论出现在何处都会从同一表示开始。"]),("2. 为允许的源位置打分",["模型在每个位置产生 query、key 和 value。Query 与 key 的点积给出一种数值匹配，再除以 key 维度的平方根。","因果掩码在 softmax 前屏蔽未来分数，因此未来位置不会获得注意力权重。"]),("3. 混合的是 value，不是词元标签",["Softmax 把允许的分数变成总和为 1 的权重。注意力输出是 value 向量的加权和。","大权重只有与它乘到的 value 一起看才有意义。权重本身不是预测的完整解释。"]),("4. 把最终状态转换为预测",["玩具模块把注意力输出与残差和前馈路径合并，再通过输出权重为词表中每项产生一个 logit。","Softmax 把 logits 变成概率。低温度让分布更尖锐，高温度让分布更平坦，但 logits 的来源不变。"]),("这个模型没有包含什么",["这个确定性模块没有预训练，不会在活动中学习，也不等同于生产语言模型。真实系统有更多层、注意力头、词表和学习参数。","注意力权重只展示一种混合运算，不能完整说明模型的推理、理解或因果原因。"])],
                "teacher":{"curriculum":"词元化、嵌入、位置、query–key 分数、因果掩码、softmax、logits、温度与证据边界。","pre":["忽略词序会丢失什么信息？","为什么下一词元预测器不能读取下一个词元？","分数与概率有什么区别？"],"post":["改变一个词元并找出第一处变化的数值。","关闭掩码后，哪一步不再是有效的下一词元预测？","改变温度时，哪些数值保持不变？","为什么最大注意力权重不是完整解释？"],"misconceptions":"一个词元总是一个单词；注意力就是理解；最大权重是完整原因；温度会改变学习权重；最高概率词元一定会被选择。"},
            },
            "vi": {
                "primer":"Transformer biến token thành vector, cho mỗi vị trí trộn thông tin trước đó được phép, rồi đổi vector cuối thành xác suất token tiếp theo. Lab giữ mọi con số đủ nhỏ để kiểm tra.",
                "terms":[("Token","Mảnh văn bản được biểu diễn bằng một ID trong bộ từ vựng đồ chơi."),("Embedding","Vector khởi đầu của token."),("Vector vị trí","Giá trị bổ sung cho biết token nằm ở đâu."),("Query, key, value","Ba vector dùng để chấm điểm và trộn thông tin."),("Causal mask","Quy tắc chặn attention tới vị trí tương lai."),("Attention weight","Hệ số đã chuẩn hóa bằng softmax để trộn value vector."),("Logit","Điểm chưa chuẩn hóa của một token tiếp theo có thể có."),("Temperature","Thang áp dụng lên logit cố định trước softmax.")],
                "scenarios":[
                    {"title":"Từ câu nhắc đến dự đoán","question":"Token cuối trở thành phân bố xác suất như thế nào?","run":"Dùng “I like cats”, bật vị trí và causal mask, rồi theo token cuối qua bốn giai đoạn.","predict":"Dự đoán vị trí nguồn được phép nào có attention weight lớn nhất.","explain":"Giải thích cách trạng thái cuối trở thành logit và xác suất."},
                    {"title":"Causal mask chặn tương lai","question":"Vì sao mô hình token tiếp theo phải che các vị trí sau?","run":"Áp dụng tình huống mask leak và so sánh cùng một hàng attention khi bật và tắt mask.","predict":"Dự đoán ô từng bị chặn nào sẽ có trọng số khác không.","explain":"Giải thích vì sao đọc token tương lai làm phép thử token tiếp theo không hợp lệ."},
                    {"title":"Thứ tự từ làm đổi biểu diễn","question":"Vì sao cùng các từ theo thứ tự khác không phải cùng đầu vào?","run":"Áp dụng tình huống thứ tự rồi so sánh vector token cuối khi bật và tắt thông tin vị trí.","predict":"Dự đoán khác biệt số đầu tiên xuất hiện ở đâu.","explain":"Giải thích vector vị trí bổ sung điều gì mà embedding không có."},
                    {"title":"Một điểm số có thể lan thay đổi về sau","question":"Thay đổi nhỏ ở query hoặc key ảnh hưởng dự đoán cuối thế nào?","run":"Áp dụng nhiễu Q/K và theo dõi score, weight, trạng thái cuối và xác suất thay đổi.","predict":"Dự đoán trọng số của token nguồn nào đổi nhiều nhất.","explain":"Giải thích vì sao đổi một score có thể đổi mọi weight đã chuẩn hóa trong hàng."},
                    {"title":"Temperature đổi độ tự tin, không đổi việc học","question":"Điều gì đổi khi temperature đổi nhưng trọng số mô hình giữ nguyên?","run":"Áp dụng tình huống temperature và so sánh logits với phân bố xác suất.","predict":"Dự đoán token đứng đầu đổi hay chỉ độ nhọn của phân bố đổi.","explain":"Giải thích vì sao temperature không huấn luyện lại mô hình."},
                ],
                "sections":[("1. Token hóa và thêm vị trí",["Tokenizer đồ chơi ánh xạ mỗi mảnh hiển thị sang ID cố định; bảng embedding biến ID thành vector.","Vector vị trí được cộng vào embedding. Không có nó, token lặp lại bắt đầu giống nhau ở mọi vị trí."]),("2. Chấm điểm các vị trí nguồn được phép",["Mô hình tạo query, key và value tại mỗi vị trí. Tích vô hướng query–key cho một mức khớp số rồi được chia theo căn bậc hai số chiều key.","Causal mask chặn điểm tương lai trước softmax, nên vị trí bị mask không có attention weight."]),("3. Trộn value, không trộn nhãn token",["Softmax biến các score được phép thành weight có tổng bằng một. Attention output là tổng có trọng số của value vector.","Weight lớn chỉ có ý nghĩa cùng value mà nó nhân. Riêng weight không giải thích đầy đủ dự đoán."]),("4. Đổi trạng thái cuối thành dự đoán",["Khối đồ chơi kết hợp attention output với đường residual và feed-forward; output weights tạo một logit cho mỗi mục từ vựng.","Softmax đổi logits thành xác suất. Temperature thấp làm phân bố nhọn hơn, cao làm phẳng hơn."]),("Mô hình này bỏ qua điều gì",["Khối xác định này không được pretrain, không học trong hoạt động và không tái hiện mô hình ngôn ngữ sản xuất. Hệ thống thật có nhiều layer, head, tham số và từ vựng hơn.","Attention weight chỉ cho thấy một phép trộn; nó không bộc lộ toàn bộ suy luận, hiểu biết hay nguyên nhân của mô hình."])],
                "teacher":{"curriculum":"Tokenization, embedding, vị trí, query–key score, causal mask, softmax, logit, temperature và giới hạn bằng chứng.","pre":["Mất thông tin gì nếu bỏ qua thứ tự token?","Vì sao bộ dự đoán token tiếp theo không được đọc token tiếp theo?","Score khác probability ở điểm nào?"],"post":["Đổi một token và tìm con số thay đổi đầu tiên.","Tắt mask: phép tính nào không còn hợp lệ cho next-token prediction?","Đổi temperature: giá trị nào giữ nguyên?","Vì sao attention weight lớn nhất không phải toàn bộ lời giải thích?"],"misconceptions":"một token luôn là một từ; attention là hiểu biết; weight lớn nhất là toàn bộ nguyên nhân; temperature đổi learned weights; token có xác suất cao nhất luôn được chọn."},
            },
            "es": {
                "primer":"Un Transformer convierte tokens en vectores, permite que cada posición mezcle información anterior permitida y transforma el vector final en probabilidades del siguiente token. El laboratorio mantiene números pequeños y revisables.",
                "terms":[("Token","Fragmento de texto representado por un ID en este vocabulario de juguete."),("Embedding","Vector inicial de un token."),("Vector de posición","Valores que indican dónde aparece un token."),("Query, key y value","Tres vectores usados para puntuar y mezclar información."),("Máscara causal","Regla que bloquea la atención a posiciones futuras."),("Peso de atención","Coeficiente normalizado con softmax para mezclar vectores de valor."),("Logit","Puntuación no normalizada de un posible siguiente token."),("Temperatura","Escala aplicada a logits fijos antes de softmax.")],
                "scenarios":[
                    {"title":"Del prompt a la predicción","question":"¿Cómo se convierte el último token en una distribución de probabilidad?","run":"Usa “I like cats” con posición y máscara causal activadas y sigue el último token por las cuatro etapas.","predict":"Predice qué posición fuente permitida recibirá el mayor peso de atención.","explain":"Explica cómo el estado final se convierte en logits y probabilidades."},
                    {"title":"La máscara causal bloquea el futuro","question":"¿Por qué un modelo del siguiente token debe ocultar posiciones posteriores?","run":"Aplica el escenario de fuga de máscara y compara la misma fila con la máscara activada y desactivada.","predict":"Predice qué celdas antes bloqueadas obtendrán peso distinto de cero.","explain":"Explica por qué leer un token futuro invalida la prueba del siguiente token."},
                    {"title":"El orden cambia la representación","question":"¿Por qué las mismas palabras en otro orden no son la misma entrada?","run":"Aplica el escenario de orden y compara el vector final con la posición activada y desactivada.","predict":"Predice dónde aparecerá la primera diferencia numérica.","explain":"Explica qué añade la posición que no contienen los embeddings solos."},
                    {"title":"Un cambio de puntuación se propaga","question":"¿Cómo puede un pequeño cambio en query o key afectar la predicción final?","run":"Aplica la perturbación Q/K y sigue la puntuación, el peso, el estado final y la probabilidad que cambian.","predict":"Predice qué peso de token fuente cambiará más.","explain":"Explica por qué cambiar una puntuación puede alterar todos los pesos normalizados de la fila."},
                    {"title":"La temperatura cambia la confianza, no el aprendizaje","question":"¿Qué cambia si varía la temperatura pero no los pesos del modelo?","run":"Aplica el escenario de temperatura y compara logits con probabilidades.","predict":"Predice si cambia el token principal o solo la concentración de la distribución.","explain":"Explica por qué la temperatura no reentrena el modelo."},
                ],
                "sections":[("1. Tokenizar y añadir posición",["El tokenizador de juguete asigna un ID fijo a cada fragmento; una tabla de embeddings convierte el ID en vector.","El vector de posición se suma al embedding. Sin él, tokens repetidos empiezan con la misma representación en cualquier lugar."]),("2. Puntuar las posiciones permitidas",["El modelo produce query, key y value en cada posición. El producto query–key mide una coincidencia numérica y se escala por la raíz de la dimensión de key.","La máscara causal bloquea puntuaciones futuras antes de softmax. Una posición enmascarada no recibe peso."]),("3. Mezclar valores, no etiquetas",["Softmax convierte las puntuaciones permitidas en pesos que suman uno. La salida de atención es la suma ponderada de los vectores value.","Un peso grande importa por el value que multiplica. Por sí solo no explica toda la predicción."]),("4. Convertir el estado final en predicción",["El bloque combina la atención con las rutas residual y feed-forward; los pesos de salida producen un logit por elemento del vocabulario.","Softmax convierte logits en probabilidades. Una temperatura menor concentra y una mayor aplana la distribución."]),("Qué deja fuera este modelo",["Este bloque determinista no está preentrenado, no aprende durante la actividad y no reproduce un modelo de producción. Los sistemas reales tienen más capas, cabezas, parámetros y vocabulario.","Los pesos de atención muestran una operación de mezcla, no todo el razonamiento, comprensión o causa del modelo."])],
                "teacher":{"curriculum":"Tokenización, embeddings, posición, puntuaciones query–key, máscara causal, softmax, logits, temperatura y límites de la evidencia.","pre":["¿Qué información se pierde al ignorar el orden?","¿Por qué no debe leer el futuro un predictor del siguiente token?","¿En qué se diferencian una puntuación y una probabilidad?"],"post":["Cambia un token e identifica el primer número que cambia.","Desactiva la máscara. ¿Qué cálculo deja de ser válido?","Cambia la temperatura. ¿Qué valores permanecen fijos?","¿Por qué el mayor peso no es toda la explicación?"],"misconceptions":"un token siempre es una palabra; atención equivale a comprensión; el mayor peso es toda la causa; la temperatura cambia los pesos aprendidos; siempre se elige el token más probable."},
            },
        },
    },
    "agent-tool-context": {
        "state_id": "stateText",
        "featured": 2,
        "settings": [
            {"scenario": "canonical"},
            {"scenario": "invalid"},
            {"scenario": "permission"},
            {"scenario": "injection"},
            {"scenario": "termination"},
        ],
        "copy": {
            "en": {
                "primer":"An agent can propose an action, but a runtime decides whether anything executes. Follow the proposal through tool lookup, argument checks, permission, execution, observation, context update, and stopping.",
                "terms":[("Proposed action","Structured output requesting a tool call or stop."),("Tool schema","The declared name, fields, and value types for a tool."),("Validation","Checking whether a proposal matches that schema."),("Authorization","Checking whether the acting principal has permission."),("Observation","Data returned after a tool executes."),("Provenance","A record of where data or context came from."),("Context update","Adding selected observations to the next decision state."),("Stop condition","A rule that ends the loop when the goal is met or progress is unsafe.")],
                "scenarios":[
                    {"title":"An observation changes the next action","question":"Why can the justified next step change after a tool returns?","run":"Use the canonical scenario and step through the first call, observation, context update, and next proposal.","predict":"Predict the next action before revealing the observation.","explain":"Explain which new fact in context changed the decision."},
                    {"title":"Invalid arguments stop before execution","question":"Where should a malformed tool call be rejected?","run":"Apply the invalid-arguments scenario and identify the first failed gate.","predict":"Predict whether authorization or tool execution will be reached.","explain":"Explain why schema validity and permission are separate checks."},
                    {"title":"Permission is a runtime boundary","question":"Why is a valid call still not automatically allowed?","run":"Apply the permission scenario, compare principals, and trace the authorization result.","predict":"Predict which principal can execute the proposed action.","explain":"Explain why the model’s request cannot grant itself permission."},
                    {"title":"Tool output is data, not an instruction","question":"How should instruction-like text inside an observation be handled?","run":"Apply the injection scenario and inspect the observation’s provenance and the next action.","predict":"Predict whether the embedded instruction should control the agent.","explain":"Explain why content and authority must remain separate."},
                    {"title":"A good agent knows when to stop","question":"When is another tool call unnecessary or unsafe?","run":"Apply the termination scenario and inspect why the runtime chooses stop.","predict":"Predict whether another call would add evidence toward the goal.","explain":"Explain how an explicit stop condition prevents pointless loops."},
                ],
                "sections":[("1. A proposal is not execution",["The model-facing step produces structured text: a tool name and arguments, or a stop action. That proposal has no external effect by itself.","The runtime first checks whether the named tool exists and whether the arguments match its declared schema."]),("2. Validity and permission answer different questions",["Validation asks whether the call is well formed. Authorization asks whether this principal may perform it in this context.","A call can be valid but denied, or invalid before permission is even considered. Keeping the gates separate makes the failure legible."]),("3. Execution returns an observation",["Only a proposal that passes the required gates reaches the simulated tool. Its result is recorded as an observation with provenance.","An observation can contain untrusted text. Its content does not inherit the authority of the runtime or user instruction."]),("4. Context guides the next decision",["The runtime selects what to add to context, preserving the source of each fact. The next proposal is based on that updated state.","The loop stops when the goal is satisfied, a required action is denied, the proposal is invalid, or no safe progress remains."]),("What this model leaves out",["This is a deterministic, local simulation. It does not call real services, authenticate real users, or create external side effects.","Production agent systems also need secure credential handling, rate limits, retries, audit logs, sandboxing, human approval, and defenses against untrusted content."])],
                "teacher":{"curriculum":"Structured tool calls, schemas, validation, authorization, observations, provenance, context updates, prompt injection boundaries, and stopping.","pre":["Does writing a tool name cause the tool to run?","What is the difference between a malformed call and a forbidden call?","Can text returned by a tool grant itself authority?"],"post":["Find the first gate that rejects the invalid call.","Switch principals. Which part of the trace changes?","Inspect the injection scenario. Which text is data?","Explain why the termination scenario should stop."],"misconceptions":"a model proposal is execution; schema validity implies permission; tool output is trusted instruction; more context is always better; an agent should keep calling tools until it is forced to stop."},
            },
            "zh": {
                "primer":"智能体可以提出动作，但是否真正执行由运行时决定。沿着工具查找、参数检查、权限、执行、观察、上下文更新和停止逐步追踪提议。",
                "terms":[("候选动作","请求工具调用或停止的结构化输出。"),("工具 schema","工具声明的名称、字段和值类型。"),("验证","检查提议是否符合 schema。"),("授权","检查当前主体是否具有权限。"),("观察结果","工具执行后返回的数据。"),("来源信息","记录数据或上下文来自哪里。"),("上下文更新","把选定的观察结果加入下一次决策状态。"),("停止条件","目标完成或无法安全推进时结束循环的规则。")],
                "scenarios":[
                    {"title":"观察结果改变下一步动作","question":"工具返回后，合理的下一步为什么会改变？","run":"使用标准情境，逐步查看第一次调用、观察结果、上下文更新和下一项提议。","predict":"揭示观察结果前先预测下一步动作。","explain":"解释上下文中的哪条新事实改变了决策。"},
                    {"title":"无效参数在执行前停止","question":"格式错误的工具调用应在哪里被拒绝？","run":"应用无效参数情境，并找出第一个失败关卡。","predict":"预测流程是否会到达授权或工具执行。","explain":"解释 schema 有效性与权限为什么是两项独立检查。"},
                    {"title":"权限是运行时边界","question":"为什么格式正确的调用也不会自动获准？","run":"应用权限情境，比较不同主体并追踪授权结果。","predict":"预测哪个主体可以执行该动作。","explain":"解释模型的请求为什么不能自行授予权限。"},
                    {"title":"工具输出是数据，不是指令","question":"观察结果中像指令的文本应怎样处理？","run":"应用注入情境，检查观察结果的来源信息和下一步动作。","predict":"预测嵌入的指令是否应控制智能体。","explain":"解释内容与权威为什么必须分开。"},
                    {"title":"好的智能体知道何时停止","question":"什么时候继续调用工具既无必要又可能不安全？","run":"应用终止情境，检查运行时为什么选择停止。","predict":"预测再次调用是否会为目标增加证据。","explain":"解释明确停止条件怎样防止无意义循环。"},
                ],
                "sections":[("1. 提议不等于执行",["面向模型的步骤只产生结构化文本：工具名称与参数，或停止动作。提议本身不会产生外部影响。","运行时先检查工具是否存在，再检查参数是否符合工具声明的 schema。"]),("2. 有效性与权限回答不同问题",["验证询问调用格式是否正确；授权询问当前主体在当前情境中是否可以执行。","调用可以格式正确但被拒绝，也可以在检查权限前就因格式错误而停止。"]),("3. 执行返回观察结果",["只有通过必要关卡的提议才会到达模拟工具。返回结果以带来源信息的观察记录。","观察结果可能包含不可信文本；其内容不会自动获得运行时或用户指令的权威。"]),("4. 上下文引导下一次决策",["运行时选择哪些观察结果加入上下文，并保留每条事实的来源。下一次提议基于更新后的状态。","目标完成、必要动作被拒、提议无效或无法安全推进时，循环应停止。"]),("这个模型没有包含什么",["这是本地的确定性模拟，不会调用真实服务、验证真实用户或产生外部副作用。","生产智能体还需要安全凭据、速率限制、重试、审计日志、沙箱、人工批准与不可信内容防护。"])],
                "teacher":{"curriculum":"结构化工具调用、schema、验证、授权、观察结果、来源、上下文更新、提示注入边界与停止。","pre":["写出工具名称会让工具自动运行吗？","格式错误与权限不足有什么区别？","工具返回的文本可以自行获得权威吗？"],"post":["找出拒绝无效调用的第一个关卡。","切换主体，跟踪中的哪一部分改变？","在注入情境中，哪些文本只是数据？","解释终止情境为什么应停止。"],"misconceptions":"模型提议就是执行；schema 有效就代表有权限；工具输出是可信指令；上下文越多越好；智能体应不断调用工具直到被迫停止。"},
            },
            "vi": {
                "primer":"Tác tử có thể đề xuất hành động, nhưng runtime quyết định có thực thi hay không. Hãy theo đề xuất qua tìm công cụ, kiểm tra đối số, quyền, thực thi, quan sát, cập nhật ngữ cảnh và dừng.",
                "terms":[("Hành động đề xuất","Đầu ra có cấu trúc yêu cầu gọi công cụ hoặc dừng."),("Tool schema","Tên, trường và kiểu giá trị đã khai báo của công cụ."),("Validation","Kiểm tra đề xuất có khớp schema hay không."),("Authorization","Kiểm tra principal hiện tại có quyền hay không."),("Observation","Dữ liệu trả về sau khi công cụ chạy."),("Provenance","Bản ghi cho biết dữ liệu hoặc ngữ cảnh đến từ đâu."),("Cập nhật ngữ cảnh","Thêm observation được chọn vào trạng thái quyết định tiếp theo."),("Điều kiện dừng","Quy tắc kết thúc khi đạt mục tiêu hoặc không thể tiến an toàn.")],
                "scenarios":[
                    {"title":"Observation làm đổi hành động tiếp theo","question":"Vì sao bước hợp lý tiếp theo có thể đổi sau khi công cụ trả về?","run":"Dùng tình huống chuẩn và bước qua lời gọi đầu, observation, cập nhật ngữ cảnh và đề xuất kế tiếp.","predict":"Dự đoán hành động tiếp theo trước khi mở observation.","explain":"Giải thích sự kiện mới nào trong ngữ cảnh làm đổi quyết định."},
                    {"title":"Đối số sai dừng trước khi thực thi","question":"Lời gọi công cụ sai dạng nên bị từ chối ở đâu?","run":"Áp dụng tình huống đối số không hợp lệ và tìm cổng lỗi đầu tiên.","predict":"Dự đoán có đi tới authorization hay execution không.","explain":"Giải thích vì sao schema validity và permission là hai kiểm tra riêng."},
                    {"title":"Quyền là ranh giới runtime","question":"Vì sao lời gọi hợp lệ vẫn chưa tự động được phép?","run":"Áp dụng tình huống permission, so sánh principal và theo kết quả authorization.","predict":"Dự đoán principal nào có thể thực thi hành động.","explain":"Giải thích vì sao yêu cầu của mô hình không thể tự cấp quyền."},
                    {"title":"Tool output là dữ liệu, không phải chỉ thị","question":"Nên xử lý văn bản giống chỉ thị trong observation thế nào?","run":"Áp dụng tình huống injection và kiểm tra provenance cùng hành động kế tiếp.","predict":"Dự đoán chỉ thị nhúng có nên điều khiển tác tử không.","explain":"Giải thích vì sao nội dung và thẩm quyền phải tách biệt."},
                    {"title":"Tác tử tốt biết lúc dừng","question":"Khi nào gọi thêm công cụ là không cần thiết hoặc không an toàn?","run":"Áp dụng tình huống termination và xem vì sao runtime chọn dừng.","predict":"Dự đoán lời gọi khác có thêm bằng chứng cho mục tiêu không.","explain":"Giải thích điều kiện dừng rõ ràng ngăn vòng lặp vô ích thế nào."},
                ],
                "sections":[("1. Đề xuất không phải thực thi",["Bước phía mô hình tạo văn bản có cấu trúc: tên công cụ và đối số, hoặc hành động dừng. Riêng đề xuất không gây tác động bên ngoài.","Runtime kiểm tra công cụ có tồn tại và đối số có khớp schema đã khai báo hay không."]),("2. Tính hợp lệ và quyền trả lời hai câu hỏi",["Validation hỏi lời gọi có đúng dạng; authorization hỏi principal có được phép trong ngữ cảnh này không.","Lời gọi có thể hợp lệ nhưng bị từ chối, hoặc sai dạng trước khi xét quyền."]),("3. Thực thi trả về observation",["Chỉ đề xuất qua đủ cổng mới tới công cụ mô phỏng. Kết quả được ghi thành observation có provenance.","Observation có thể chứa văn bản không đáng tin. Nội dung ấy không kế thừa thẩm quyền của runtime hay người dùng."]),("4. Ngữ cảnh dẫn hướng quyết định tiếp",["Runtime chọn dữ liệu đưa vào ngữ cảnh và giữ nguồn của từng sự kiện. Đề xuất sau dựa trên trạng thái đã cập nhật.","Vòng lặp dừng khi đạt mục tiêu, hành động cần thiết bị từ chối, đề xuất sai, hoặc không còn tiến bộ an toàn."]),("Mô hình này bỏ qua điều gì",["Đây là mô phỏng cục bộ, xác định; không gọi dịch vụ thật, xác thực người dùng thật hay tạo tác động ngoài.","Hệ thống sản xuất còn cần quản lý credential, rate limit, retry, audit log, sandbox, phê duyệt con người và phòng vệ nội dung không tin cậy."])],
                "teacher":{"curriculum":"Tool call có cấu trúc, schema, validation, authorization, observation, provenance, cập nhật ngữ cảnh, ranh giới prompt injection và dừng.","pre":["Viết tên công cụ có làm nó chạy không?","Lời gọi sai dạng khác lời gọi bị cấm thế nào?","Văn bản từ công cụ có thể tự cấp thẩm quyền không?"],"post":["Tìm cổng đầu tiên chặn lời gọi sai.","Đổi principal: phần nào của trace thay đổi?","Trong tình huống injection, văn bản nào chỉ là dữ liệu?","Giải thích vì sao tình huống termination phải dừng."],"misconceptions":"đề xuất của mô hình là thực thi; schema hợp lệ nghĩa là có quyền; tool output là chỉ thị đáng tin; thêm ngữ cảnh luôn tốt; tác tử phải gọi công cụ cho đến khi bị buộc dừng."},
            },
            "es": {
                "primer":"Un agente puede proponer una acción, pero el runtime decide si se ejecuta. Sigue la propuesta por búsqueda de herramienta, argumentos, permiso, ejecución, observación, actualización de contexto y parada.",
                "terms":[("Acción propuesta","Salida estructurada que solicita una herramienta o detenerse."),("Esquema de herramienta","Nombre, campos y tipos declarados para una herramienta."),("Validación","Comprobar si la propuesta coincide con el esquema."),("Autorización","Comprobar si el principal actual tiene permiso."),("Observación","Datos devueltos después de ejecutar una herramienta."),("Procedencia","Registro del origen de datos o contexto."),("Actualización de contexto","Añadir observaciones elegidas al siguiente estado de decisión."),("Condición de parada","Regla que termina el ciclo al cumplir la meta o no poder avanzar con seguridad.")],
                "scenarios":[
                    {"title":"Una observación cambia la siguiente acción","question":"¿Por qué puede cambiar el paso justificado tras la respuesta de una herramienta?","run":"Usa el escenario canónico y recorre llamada, observación, contexto y siguiente propuesta.","predict":"Predice la siguiente acción antes de revelar la observación.","explain":"Explica qué hecho nuevo del contexto cambió la decisión."},
                    {"title":"Los argumentos inválidos paran antes de ejecutar","question":"¿Dónde debe rechazarse una llamada mal formada?","run":"Aplica el escenario de argumentos inválidos e identifica la primera puerta fallida.","predict":"Predice si se llegará a autorización o ejecución.","explain":"Explica por qué validez del esquema y permiso son comprobaciones distintas."},
                    {"title":"El permiso es un límite del runtime","question":"¿Por qué una llamada válida no queda permitida automáticamente?","run":"Aplica el escenario de permiso, compara principales y sigue el resultado de autorización.","predict":"Predice qué principal puede ejecutar la acción.","explain":"Explica por qué la petición del modelo no puede concederse permiso a sí misma."},
                    {"title":"La salida de una herramienta es dato, no instrucción","question":"¿Cómo debe tratarse texto con aspecto de instrucción dentro de una observación?","run":"Aplica el escenario de inyección e inspecciona procedencia y siguiente acción.","predict":"Predice si la instrucción incrustada debe controlar al agente.","explain":"Explica por qué contenido y autoridad deben permanecer separados."},
                    {"title":"Un buen agente sabe cuándo parar","question":"¿Cuándo otra llamada es innecesaria o insegura?","run":"Aplica el escenario de terminación e inspecciona por qué el runtime se detiene.","predict":"Predice si otra llamada aportaría evidencia para la meta.","explain":"Explica cómo una condición explícita evita bucles inútiles."},
                ],
                "sections":[("1. Una propuesta no es ejecución",["El paso del modelo produce texto estructurado: herramienta y argumentos, o una acción de parada. Por sí solo no tiene efecto externo.","El runtime comprueba que la herramienta existe y que los argumentos cumplen el esquema."]),("2. Validez y permiso responden preguntas distintas",["La validación pregunta si la llamada está bien formada. La autorización pregunta si este principal puede realizarla en este contexto.","Una llamada puede ser válida y denegada, o inválida antes de considerar permisos."]),("3. La ejecución devuelve una observación",["Solo una propuesta que supera las puertas llega a la herramienta simulada. El resultado se registra con su procedencia.","Una observación puede contener texto no confiable. Su contenido no hereda autoridad del runtime ni del usuario."]),("4. El contexto guía la siguiente decisión",["El runtime elige qué añadir al contexto y conserva el origen de cada dato. La siguiente propuesta usa ese estado actualizado.","El ciclo para al cumplir la meta, denegarse una acción necesaria, ser inválida la propuesta o no quedar progreso seguro."]),("Qué deja fuera este modelo",["Es una simulación local y determinista: no llama servicios, autentica usuarios ni produce efectos externos reales.","Los sistemas de producción necesitan además credenciales seguras, límites, reintentos, auditoría, aislamiento, aprobación humana y defensas ante contenido no confiable."])],
                "teacher":{"curriculum":"Llamadas estructuradas, esquemas, validación, autorización, observaciones, procedencia, contexto, límites ante inyección y parada.","pre":["¿Escribir el nombre de una herramienta hace que se ejecute?","¿Qué diferencia hay entre llamada mal formada y prohibida?","¿Puede el texto de una herramienta otorgarse autoridad?"],"post":["Encuentra la primera puerta que rechaza la llamada inválida.","Cambia el principal. ¿Qué parte de la traza cambia?","En la inyección, ¿qué texto es solo dato?","Explica por qué debe parar el escenario de terminación."],"misconceptions":"una propuesta es ejecución; un esquema válido implica permiso; la salida de herramienta es instrucción confiable; más contexto siempre es mejor; el agente debe seguir llamando hasta que se le obligue a parar."},
            },
        },
    },
    "minimax-alpha-beta": {
        "state_id": "textState",
        "featured": 2,
        "settings": [
            {"scenario": "simple_backup", "algorithm": "minimax", "order": "configured"},
            {"scenario": "greedy_trap", "algorithm": "minimax", "order": "configured"},
            {"scenario": "first_prune", "algorithm": "alpha_beta", "order": "configured"},
            {"scenario": "good_ordering", "algorithm": "alpha_beta", "order": "configured"},
            {"scenario": "no_prune", "algorithm": "alpha_beta", "order": "configured"},
        ],
        "copy": {
            "en": {
                "primer":"Minimax assumes both players choose optimally: MAX keeps the largest backed-up value and MIN keeps the smallest. Alpha-beta returns the same answer while skipping branches that current bounds prove cannot matter.",
                "terms":[("Game tree","Possible moves arranged as parent and child positions."),("Terminal utility","The score assigned to a finished position."),("MAX node","A turn that keeps the largest child value."),("MIN node","A turn that keeps the smallest child value."),("Minimax value","The result backed up under optimal choices by both players."),("Alpha (α)","The best value MAX can already guarantee on the current path."),("Beta (β)","The best value MIN can already guarantee on the current path."),("Cutoff","A proof that remaining siblings cannot change the ancestor decision.")],
                "scenarios":[
                    {"title":"Back up a simple tree","question":"How do alternating MIN and MAX choices determine the root value?","run":"Use the simple backup tree with minimax and reveal the trace one step at a time.","predict":"Predict each MIN value, then the move MAX will choose.","explain":"Explain why the largest visible leaf alone does not determine the root move."},
                    {"title":"A greedy leaf can be a trap","question":"Why can a branch containing the largest leaf still be the worse move?","run":"Apply the greedy-trap tree and compare the best visible leaf with the value MIN can force.","predict":"Predict whether MAX chooses branch A or B.","explain":"Explain why a player chooses a strategy against an opponent, not a single leaf."},
                    {"title":"Find the first safe prune","question":"When do alpha and beta prove that a sibling cannot matter?","run":"Apply the first-prune scenario, step until α ≥ β, and identify the nodes not evaluated.","predict":"Predict which sibling will be skipped and what root value remains.","explain":"Explain why the skipped node cannot change the ancestor choice."},
                    {"title":"Move order changes work, not the answer","question":"How can the same tree require fewer evaluated leaves?","run":"Use alpha-beta on the good-ordering tree, save the run, then reverse the sibling order.","predict":"Predict which order exposes useful bounds earlier.","explain":"Explain why both orders must return the same minimax value."},
                    {"title":"Some trees offer no useful cutoff","question":"Why does alpha-beta sometimes visit every leaf?","run":"Apply the no-prune scenario and reveal the full alpha-beta trace.","predict":"Predict whether any bound becomes strong enough to skip a sibling.","explain":"Explain why alpha-beta’s best-case speedup is not guaranteed."},
                ],
                "sections":[("1. Define the game before searching",["A game tree lists legal continuations. Terminal utilities are part of the problem definition, not values invented by minimax.","This lab assumes a finite, deterministic, two-player, zero-sum, perfect-information game and optimal play by both sides."]),("2. Back values from leaves to the root",["At a MAX node, keep the largest returned child value. At a MIN node, keep the smallest. Repeating that rule gives the root minimax value and an optimal move.","A high leaf is not enough: the opposing player chooses among the leaves available on their turn."]),("3. Carry alpha and beta bounds",["Alpha is the best value MAX can already guarantee along the current path. Beta is the best value MIN can already guarantee.","Once alpha is at least beta, remaining siblings cannot improve the decision for the player whose ancestor already has the stronger option."]),("4. Pruning preserves the exact answer",["A pruned node still exists in the game tree. The algorithm merely avoids evaluating it because the current bounds prove it cannot affect the root choice.","Move ordering changes when strong bounds appear. It can reduce work dramatically, but it cannot change the exact minimax result on the same fixed tree."]),("What this model leaves out",["Large games require depth limits, heuristic evaluation, transposition tables, iterative deepening, and other search engineering.","Games with chance, hidden information, simultaneous moves, more than two players, or non-zero-sum payoffs need different models."])],
                "teacher":{"curriculum":"Game trees, terminal utility, alternating MAX/MIN backup, optimal play, alpha and beta bounds, safe cutoffs, and move ordering.","pre":["Who chooses the next node at a MIN turn?","Can the largest leaf determine MAX’s move by itself?","What would make it safe not to inspect a branch?"],"post":["Back up the simple tree without running the applet.","Find the exact event where the first cutoff becomes safe.","Reverse move order and compare evaluated leaves.","Explain why pruned means not evaluated, not removed from the game."],"misconceptions":"MAX always chooses the largest visible leaf; pruning changes the answer; pruned nodes do not exist; alpha-beta always prunes; move ordering changes the game value."},
            },
            "zh": {
                "primer":"Minimax 假设双方都做最优选择：MAX 保留较大的回传值，MIN 保留较小的回传值。Alpha-Beta 返回相同答案，同时跳过当前边界已证明无关的分支。",
                "terms":[("博弈树","按父子关系排列的可能行动与局面。"),("终局效用值","赋给结束局面的分数。"),("MAX 节点","保留最大子节点值的一方回合。"),("MIN 节点","保留最小子节点值的一方回合。"),("Minimax 值","双方都最优选择时向上回传的结果。"),("Alpha（α）","当前路径上 MAX 已能保证的最佳值。"),("Beta（β）","当前路径上 MIN 已能保证的最佳值。"),("截断","证明剩余兄弟节点不会改变祖先决策。")],
                "scenarios":[
                    {"title":"回传一棵简单博弈树","question":"交替的 MIN 与 MAX 选择怎样决定根节点值？","run":"使用简单回传树与 minimax，逐步揭示跟踪。","predict":"先预测各 MIN 节点值，再预测 MAX 选择的行动。","explain":"解释为什么只看最大的叶节点不能决定根节点行动。"},
                    {"title":"贪心叶节点可能是陷阱","question":"为什么包含最大叶值的分支仍可能是较差行动？","run":"应用贪心陷阱树，比较最大的可见叶值与 MIN 能迫使得到的值。","predict":"预测 MAX 会选择 A 还是 B。","explain":"解释玩家为什么是在对抗对手策略，而不是选择单个叶节点。"},
                    {"title":"找到第一次安全剪枝","question":"Alpha 与 beta 何时能证明某个兄弟节点无关？","run":"应用首次剪枝情境，单步执行到 α ≥ β，并找出未评估节点。","predict":"预测哪个兄弟节点会被跳过，以及根节点值是否保持。","explain":"解释被跳过节点为什么不能改变祖先选择。"},
                    {"title":"行动顺序改变工作量，不改变答案","question":"同一棵树怎样只评估更少叶节点？","run":"用 alpha-beta 运行良好顺序，保存结果，再反转兄弟节点顺序。","predict":"预测哪种顺序会更早产生有用边界。","explain":"解释两种顺序为什么必须返回相同 minimax 值。"},
                    {"title":"有些树无法有效剪枝","question":"为什么 alpha-beta 有时仍会访问所有叶节点？","run":"应用无剪枝情境并揭示完整 alpha-beta 跟踪。","predict":"预测是否会有边界强到足以跳过兄弟节点。","explain":"解释 alpha-beta 的最佳加速为什么没有保证。"},
                ],
                "sections":[("1. 搜索前先定义博弈",["博弈树列出合法的后续行动。终局效用值属于问题定义，并不是 minimax 生成的数值。","本实验假设有限、确定性、双人、零和、完全信息博弈，并假设双方最优行动。"]),("2. 从叶节点向根节点回传",["MAX 节点保留最大的返回值，MIN 节点保留最小的返回值。重复这条规则即可得到根节点 minimax 值与最优行动。","一个高叶值并不足够，因为对手会在自己的回合中选择可到达的叶节点。"]),("3. 携带 alpha 与 beta 边界",["Alpha 是当前路径上 MAX 已能保证的最佳值；beta 是 MIN 已能保证的最佳值。","当 alpha 至少等于 beta 时，剩余兄弟节点无法改善祖先处已有的更强选择。"]),("4. 剪枝保留精确答案",["被剪枝节点仍存在于博弈树中。算法只是因为边界已证明它不会影响根节点选择而不再评估。","行动顺序会改变强边界何时出现，因此能改变工作量，却不能改变同一固定树上的精确 minimax 结果。"]),("这个模型没有包含什么",["大型游戏还需要深度限制、启发式评估、置换表、迭代加深等搜索工程。","含随机性、隐藏信息、同时行动、多人或非零和收益的博弈需要不同模型。"])],
                "teacher":{"curriculum":"博弈树、终局效用值、MAX/MIN 交替回传、最优行动、alpha/beta 边界、安全截断与行动顺序。","pre":["在 MIN 回合是谁选择下一节点？","最大叶值能否单独决定 MAX 的行动？","什么条件能让不检查某分支变得安全？"],"post":["不运行 applet，手工回传简单树。","找出第一次截断变得安全的精确事件。","反转行动顺序并比较评估叶节点数。","解释“被剪枝”为什么表示未评估，而不是从博弈中删除。"],"misconceptions":"MAX 总选择最大可见叶值；剪枝改变答案；被剪枝节点不存在；alpha-beta 总能剪枝；行动顺序会改变博弈值。"},
            },
            "vi": {
                "primer":"Minimax giả định cả hai bên chọn tối ưu: MAX giữ giá trị lớn nhất truyền lên, MIN giữ nhỏ nhất. Alpha-beta trả cùng đáp án nhưng bỏ qua nhánh mà các cận đã chứng minh không thể quan trọng.",
                "terms":[("Cây trò chơi","Các nước đi có thể được sắp theo vị trí cha và con."),("Utility ở trạng thái kết thúc","Điểm gán cho một vị trí đã kết thúc."),("Nút MAX","Lượt giữ giá trị con lớn nhất."),("Nút MIN","Lượt giữ giá trị con nhỏ nhất."),("Giá trị minimax","Kết quả truyền lên khi cả hai bên chọn tối ưu."),("Alpha (α)","Giá trị tốt nhất MAX đã có thể bảo đảm trên đường hiện tại."),("Beta (β)","Giá trị tốt nhất MIN đã có thể bảo đảm trên đường hiện tại."),("Cutoff","Bằng chứng rằng các nút anh em còn lại không thể đổi quyết định tổ tiên.")],
                "scenarios":[
                    {"title":"Truyền giá trị lên cây đơn giản","question":"Lựa chọn MIN và MAX xen kẽ quyết định giá trị gốc thế nào?","run":"Dùng cây simple backup với minimax và mở trace từng bước.","predict":"Dự đoán từng giá trị MIN rồi nước đi MAX chọn.","explain":"Giải thích vì sao lá lớn nhất nhìn thấy không tự quyết định nước đi ở gốc."},
                    {"title":"Một lá hấp dẫn có thể là bẫy","question":"Vì sao nhánh chứa lá lớn nhất vẫn có thể là nước đi tệ hơn?","run":"Áp dụng cây greedy trap và so sánh lá lớn nhất với giá trị MIN có thể ép.","predict":"Dự đoán MAX chọn A hay B.","explain":"Giải thích vì sao người chơi chọn chiến lược trước đối thủ, không chọn riêng một lá."},
                    {"title":"Tìm lần cắt tỉa an toàn đầu tiên","question":"Khi nào alpha và beta chứng minh một nút anh em không thể quan trọng?","run":"Áp dụng first prune, bước tới α ≥ β và xác định nút không được đánh giá.","predict":"Dự đoán nút nào bị bỏ qua và giá trị gốc còn bao nhiêu.","explain":"Giải thích vì sao nút bị bỏ qua không thể đổi lựa chọn của tổ tiên."},
                    {"title":"Thứ tự nước đi đổi công việc, không đổi đáp án","question":"Cùng một cây có thể cần đánh giá ít lá hơn thế nào?","run":"Chạy alpha-beta với good ordering, lưu lần chạy rồi đảo thứ tự anh em.","predict":"Dự đoán thứ tự nào tạo cận hữu ích sớm hơn.","explain":"Giải thích vì sao cả hai thứ tự phải trả cùng giá trị minimax."},
                    {"title":"Một số cây không cho cutoff hữu ích","question":"Vì sao alpha-beta đôi khi vẫn thăm mọi lá?","run":"Áp dụng no prune và mở toàn bộ trace alpha-beta.","predict":"Dự đoán có cận nào đủ mạnh để bỏ qua nút anh em không.","explain":"Giải thích vì sao tăng tốc tốt nhất của alpha-beta không được bảo đảm."},
                ],
                "sections":[("1. Xác định trò chơi trước khi tìm",["Cây trò chơi liệt kê các tiếp diễn hợp lệ. Utility ở trạng thái kết thúc là dữ liệu bài toán, không phải giá trị minimax tự tạo.","Lab giả định trò chơi hữu hạn, xác định, hai người, tổng bằng không, thông tin hoàn hảo và cả hai chơi tối ưu."]),("2. Truyền giá trị từ lá lên gốc",["Ở nút MAX, giữ giá trị con lớn nhất; ở nút MIN, giữ nhỏ nhất. Lặp quy tắc cho giá trị minimax ở gốc và nước đi tối ưu.","Một lá cao chưa đủ vì đối thủ chọn trong các lá tới được ở lượt của họ."]),("3. Mang theo cận alpha và beta",["Alpha là giá trị tốt nhất MAX đã bảo đảm trên đường hiện tại; beta là giá trị tốt nhất MIN đã bảo đảm.","Khi alpha ít nhất bằng beta, các nút anh em còn lại không thể cải thiện quyết định ở tổ tiên đã có lựa chọn mạnh hơn."]),("4. Pruning giữ nguyên đáp án chính xác",["Nút bị prune vẫn tồn tại trong cây. Thuật toán chỉ không đánh giá vì cận đã chứng minh nó không ảnh hưởng lựa chọn gốc.","Thứ tự nước đi đổi lúc cận mạnh xuất hiện và có thể giảm nhiều công việc, nhưng không đổi kết quả minimax chính xác."]),("Mô hình này bỏ qua điều gì",["Trò chơi lớn cần giới hạn độ sâu, heuristic evaluation, transposition table, iterative deepening và kỹ thuật tìm kiếm khác.","Trò chơi có ngẫu nhiên, thông tin ẩn, nước đi đồng thời, nhiều hơn hai người hay không zero-sum cần mô hình khác."])],
                "teacher":{"curriculum":"Cây trò chơi, terminal utility, MAX/MIN backup, chơi tối ưu, cận alpha/beta, cutoff an toàn và thứ tự nước đi.","pre":["Ai chọn nút tiếp theo ở lượt MIN?","Lá lớn nhất có tự quyết định nước đi MAX không?","Điều gì làm việc không xem một nhánh trở nên an toàn?"],"post":["Tự truyền giá trị cây đơn giản trước khi chạy applet.","Tìm đúng sự kiện nơi cutoff đầu tiên trở nên an toàn.","Đảo thứ tự và so sánh số lá được đánh giá.","Giải thích vì sao pruned nghĩa là không đánh giá, không phải bị xóa khỏi trò chơi."],"misconceptions":"MAX luôn chọn lá lớn nhất nhìn thấy; pruning đổi đáp án; nút bị prune không tồn tại; alpha-beta luôn prune; thứ tự nước đi đổi giá trị trò chơi."},
            },
            "es": {
                "primer":"Minimax supone que ambos jugadores eligen de forma óptima: MAX conserva el mayor valor propagado y MIN el menor. Alpha-beta devuelve la misma respuesta mientras omite ramas que los límites demuestran irrelevantes.",
                "terms":[("Árbol de juego","Movimientos posibles organizados como posiciones padre e hijas."),("Utilidad terminal","Puntuación asignada a una posición final."),("Nodo MAX","Turno que conserva el mayor valor hijo."),("Nodo MIN","Turno que conserva el menor valor hijo."),("Valor minimax","Resultado propagado con elecciones óptimas de ambos jugadores."),("Alpha (α)","Mejor valor que MAX ya puede garantizar en la ruta actual."),("Beta (β)","Mejor valor que MIN ya puede garantizar en la ruta actual."),("Corte","Prueba de que los hermanos restantes no pueden cambiar la decisión del ancestro.")],
                "scenarios":[
                    {"title":"Propagar un árbol sencillo","question":"¿Cómo determinan MIN y MAX alternos el valor de la raíz?","run":"Usa el árbol sencillo con minimax y revela la traza paso a paso.","predict":"Predice cada valor MIN y después la jugada que elegirá MAX.","explain":"Explica por qué la mayor hoja visible no determina por sí sola la jugada raíz."},
                    {"title":"Una hoja atractiva puede ser una trampa","question":"¿Por qué una rama con la mayor hoja puede ser la peor jugada?","run":"Aplica la trampa voraz y compara la mayor hoja con el valor que MIN puede forzar.","predict":"Predice si MAX elige A o B.","explain":"Explica por qué se elige una estrategia frente a un rival, no una sola hoja."},
                    {"title":"Encontrar la primera poda segura","question":"¿Cuándo demuestran alpha y beta que un hermano ya no importa?","run":"Aplica la primera poda, avanza hasta α ≥ β e identifica los nodos no evaluados.","predict":"Predice qué hermano se omitirá y qué valor conservará la raíz.","explain":"Explica por qué el nodo omitido no puede cambiar la elección del ancestro."},
                    {"title":"El orden cambia el trabajo, no la respuesta","question":"¿Cómo puede el mismo árbol requerir menos hojas evaluadas?","run":"Usa alpha-beta con buen orden, guarda la ejecución y luego invierte los hermanos.","predict":"Predice qué orden expone antes límites útiles.","explain":"Explica por qué ambos órdenes deben devolver el mismo valor minimax."},
                    {"title":"Algunos árboles no ofrecen cortes útiles","question":"¿Por qué alpha-beta a veces visita todas las hojas?","run":"Aplica el escenario sin poda y revela toda la traza alpha-beta.","predict":"Predice si algún límite bastará para omitir un hermano.","explain":"Explica por qué la mejor aceleración de alpha-beta no está garantizada."},
                ],
                "sections":[("1. Definir el juego antes de buscar",["El árbol enumera continuaciones legales. Las utilidades terminales forman parte del problema; minimax no las inventa.","El laboratorio supone un juego finito, determinista, de dos jugadores, suma cero, información perfecta y juego óptimo."]),("2. Propagar valores de las hojas a la raíz",["MAX conserva el mayor valor hijo y MIN el menor. Repetir la regla produce el valor minimax raíz y una jugada óptima.","Una hoja alta no basta: el rival elige entre las hojas disponibles en su turno."]),("3. Llevar límites alpha y beta",["Alpha es lo mejor que MAX ya garantiza en la ruta; beta es lo mejor que MIN ya garantiza.","Cuando alpha es al menos beta, los hermanos restantes no mejoran la decisión del ancestro que ya posee una opción más fuerte."]),("4. La poda conserva la respuesta exacta",["Un nodo podado sigue en el árbol. El algoritmo evita evaluarlo porque los límites prueban que no afecta la elección raíz.","El orden cambia cuándo aparecen límites fuertes y puede reducir trabajo, pero no cambia el minimax exacto del mismo árbol."]),("Qué deja fuera este modelo",["Los juegos grandes requieren límites de profundidad, evaluación heurística, tablas de transposición, profundización iterativa y otras técnicas.","Azar, información oculta, jugadas simultáneas, más jugadores o pagos no nulos requieren otros modelos."])],
                "teacher":{"curriculum":"Árboles, utilidad terminal, respaldo MAX/MIN, juego óptimo, límites alpha/beta, cortes seguros y orden de jugadas.","pre":["¿Quién elige el siguiente nodo en un turno MIN?","¿Puede la mayor hoja decidir sola la jugada MAX?","¿Qué haría seguro no revisar una rama?"],"post":["Propaga el árbol sencillo sin ejecutar el applet.","Encuentra el evento exacto del primer corte seguro.","Invierte el orden y compara hojas evaluadas.","Explica por qué podado significa no evaluado, no eliminado del juego."],"misconceptions":"MAX siempre elige la mayor hoja visible; la poda cambia la respuesta; los nodos podados no existen; alpha-beta siempre poda; el orden cambia el valor del juego."},
            },
        },
    },
}
